import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <meta name="impact-site-verification" content="cd7c222f-cec2-474f-87c4-586f0847f263" />
        <meta name="impact-site-verification" value="cd7c222f-cec2-474f-87c4-586f0847f263" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
