import os
import json
import asyncio
import sys
import datetime
from tools.browser_skill import browser_skill

async def run_audit(url, session_id="audit_session"):
    print(f"Starting SEO Audit for: {url}")
    
    command = {
        "action": "extract_seo",
        "url": url,
        "session_id": session_id,
        "take_screenshot": True
    }
    
    result = await browser_skill(command)
    
    if result.get("status") == "error":
        print(f"Audit failed: {result.get('message')}")
        return
    
    seo = result.get("seo_data", {})
    perf = result.get("performance", {})
    
    # Format the report
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    safe_url = url.replace("https://", "").replace("http://", "").replace("/", "_").replace(":", "")
    filename = f"audit_{safe_url}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path = os.path.join("tru", "Projects", "SEO_Reports", filename)
    
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    
    report_content = f"""# SEO Audit Report: {url}
**Date**: {timestamp}
**Status**: SUCCESS

## 📊 Technical SEO
- **Title**: {seo.get('title')}
- **Description**: {seo.get('meta_description')}
- **Canonical**: {seo.get('canonical')}
- **Robots**: {seo.get('robots')}
- **Viewport**: {seo.get('viewport')}

## 🏗️ Content Structure
- **H1 Tags**: {", ".join(seo.get('h1', [])) if seo.get('h1') else "None"}
- **H2 Tags (Top 10)**: {", ".join(seo.get('h2', [])) if seo.get('h2') else "None"}
- **Link Count**: {seo.get('links_count')}
- **Image Count**: {seo.get('images_count')}
- **Images Missing Alt**: {seo.get('images_without_alt')}

## 🧠 Structured Data (Schema.org)
- **Detected**: {"Yes" if seo.get('schema_org') else "No"}
- **Count**: {len(seo.get('schema_org', []))}
- **Types**: {", ".join(set([s.get('@type', 'Unknown') for s in seo.get('schema_org', []) if isinstance(s, dict)])) if seo.get('schema_org') else "None"}

## ⚡ Performance (ms)
- **DOM Interactive**: {perf.get('dom_interactive') if isinstance(perf, dict) else "N/A"}
- **DOM Complete**: {perf.get('dom_complete') if isinstance(perf, dict) else "N/A"}
- **Load Event**: {perf.get('load_event') if isinstance(perf, dict) else "N/A"}

## 📸 Screenshots
- **Path**: {result.get('screenshot_path', 'None')}

---
*Generated by Anti-Gravity SEO Engine v1.0*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print(f"Report saved to: {report_path}")
    return report_path

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/seo_audit_engine.py <url>")
        sys.exit(1)
    
    target_url = sys.argv[1]
    asyncio.run(run_audit(target_url))
